### ISSUE TITLE
Prefix set incorrectly

### ISSUE THREAD

**Issue by klauer** [pcdshub/lcls-plc-txi-hxr-vac#10]
## Issue

The current PV prefix is set to: `PLC:txi_hxr_vac`

https://github.com/pcdshub/lcls-plc-txi-hxr-vac/blob/9ae1e24501fee27fa4773c07859668f6058f8ccd/iocBoot/ioc-txi-hxr-vac/Makefile#L12

This should be, perhaps, `PLC:TXI:HXR:VAC` (with the other one as `PLC:TXI:SXR:VAC`) or similar to conform with other PLC projects.

**Comment by jyotiphy** [comment]
@klauer That is right! This actually made me think that we use LFE/KFE instead of HXR/SXR. I don't know why I picked HXR/SXR :(

**Comment by jyotiphy** [comment]
@klauer Do you suggest to change the project/repo names or this is acceptable ? It'll be little messy to change it, but now is the good time as we have just started building TXI.

**Comment by klauer** [comment]
I think the PV names matter the most, so I'd recommend fixing `PREFIX` at least.

The project names are much less important, but it _might_ be nice for consistency.

**Comment by jyotiphy** [comment]
The PV names are fixed.
